from django.conf.urls import patterns, url
from cargabase.views import DepartamentoCreate, DepartamentoList, DepartamentoDetail,\
    DepartamentoUpdate, CategoriaDetail, CategoriaUpdate, RecursoNaturalCreate,\
    RecursoNaturalDetail, RecursoNaturalList, RecursoNaturalUpdate
from cargabase.views import RecursoCulturalCreate, RecursoCulturalDetail, RecursoCulturalList,\
    RecursoCulturalUpdate
from cargabase.views import CategoriaCreate, CategoriaList
from . import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^departamento/list/$', 
                           DepartamentoList.as_view(), 
                           name='departamento-list'),
                       url(r'^departamento/add/$', 
                           DepartamentoCreate.as_view(), 
                           name='departamento-add'),
                       url(r'^departamento/(?P<pk>\d+)/$', 
                           DepartamentoDetail.as_view(), 
                           name='departamento-detail'),
                       url(r'^departamento/(?P<pk>\d+)/update/$', 
                           DepartamentoUpdate.as_view(), 
                           name="departamento-update"),
                       url(r'^categoria/add/$', 
                           CategoriaCreate.as_view(), 
                           name='categoria-add'),
                       url(r'^categoria/(?P<pk>\d+)/$', 
                           CategoriaDetail.as_view(), 
                           name='categoria-detail'),
                       url(r'^categoria/list/$', 
                           CategoriaList.as_view(), 
                           name='categoria-list'),
                       url(r'^categoria/(?P<pk>\d+)/update/$', 
                           CategoriaUpdate.as_view(), 
                           name="categoria-update"),
                       url(r'^recursonatural/add/$', 
                           RecursoNaturalCreate.as_view(), 
                           name='recursonatural-add'),
                       url(r'^recursonatural/(?P<pk>\d+)/$', 
                           RecursoNaturalDetail.as_view(), 
                           name='recursonatural-detail'),
                       url(r'^recursonatural/list/$', 
                           RecursoNaturalList.as_view(), 
                           name='recursonatural-list'),
                       url(r'^recursonatural/(?P<pk>\d+)/update/$', 
                           RecursoNaturalUpdate.as_view(), 
                           name="recursonatural-update"),
                       url(r'^recursocultural/add/$', 
                           RecursoCulturalCreate.as_view(), 
                           name='recursocultural-add'),
                       url(r'^recursocultural/(?P<pk>\d+)/$', 
                           RecursoCulturalDetail.as_view(), 
                           name='recursocultural-detail'),
                       url(r'^recursocultural/list/$', 
                           RecursoCulturalList.as_view(), 
                           name='recursocultural-list'),
                       url(r'^recursocultural/(?P<pk>\d+)/update/$', 
                           RecursoCulturalUpdate.as_view(), 
                           name="recursocultural-update"),
                       )